version: '3.8'

services:

  langflow:
    image: logspace/langflow:latest
    container_name: klypup_langflow
    restart: always
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_PORT=7860
      - LANGFLOW_HOST=0.0.0.0

  backend:
    build: ./backend
    container_name: klypup_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres.wuuatsqfkuqntumnloaw:placeholder@aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres}
      - SUPABASE_URL=https://wuuatsqfkuqntumnloaw.supabase.co
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SECRET_KEY=another_secret_key
      - CORS_ORIGINS=http://localhost,http://localhost:5173,http://127.0.0.1
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - AI_PROVIDER=groq

  frontend:
    build: ./frontend
    container_name: klypup_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

