steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.worker
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-south1-docker.pkg.dev/solid-coral-506712-h2/klypup/klypup-recommendation-worker:latest
options:
  logging: CLOUD_LOGGING_ONLY
