import { AnimatePresence, motion } from "framer-motion";
import { Activity, BellRing, CheckCircle2, CircleAlert, Clock3, Command, ExternalLink, Loader2, Play, Radio, RefreshCw, Search, Terminal, Wifi, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { usePricingData } from "../hooks/usePricingData";
import { acknowledgePriceDropAlert, apiClient, getPriceDropAlerts } from "../services/api";
import type { PriceDropAlert, Product } from "../types/domain";
import { Badge, Button, GlassCard, SectionTitle, ToastStack, useToasts } from "../components/ui";

type PlatformState = "active" | "idle" | "alert" | "running";
interface Platform { name: string; code: string; color: string; cadence: string; coverage: number; state: PlatformState; lastStatus: number; items: number; latency: string; }
interface LogLine { id: number; time: string; platform: string; status: number | "…"; message: string; tone: "ok" | "warn" | "error"; }

const initialPlatforms: Platform[] = [
  { name: "Amazon", code: "AZ", color: "#f59e0b", cadence: "5 min", coverage: 98, state: "active", lastStatus: 200, items: 248, latency: "1.2s" },
  { name: "Flipkart", code: "FK", color: "#60a5fa", cadence: "10 min", coverage: 96, state: "active", lastStatus: 200, items: 182, latency: "1.6s" },
  { name: "Ajio", code: "AJ", color: "#f472b6", cadence: "15 min", coverage: 91, state: "active", lastStatus: 200, items: 114, latency: "2.1s" },
  { name: "Croma", code: "CR", color: "#34d399", cadence: "15 min", coverage: 88, state: "idle", lastStatus: 204, items: 74, latency: "2.7s" },
  { name: "Myntra", code: "MY", color: "#fb7185", cadence: "30 min", coverage: 87, state: "alert", lastStatus: 429, items: 96, latency: "4.9s" },
  { name: "Nykaa", code: "NK", color: "#f9a8d4", cadence: "30 min", coverage: 93, state: "active", lastStatus: 200, items: 121, latency: "2.4s" },
  { name: "Reliance Digital", code: "RD", color: "#a78bfa", cadence: "20 min", coverage: 90, state: "active", lastStatus: 200, items: 83, latency: "1.9s" },
  { name: "Tata CLiQ", code: "TC", color: "#c084fc", cadence: "20 min", coverage: 85, state: "idle", lastStatus: 204, items: 69, latency: "3.0s" },
];
const seedLogs: LogLine[] = [
  { id: 1, time: "17:58:42", platform: "Amazon", status: 200, message: "Matched 248 catalog items · price payload normalized", tone: "ok" },
  { id: 2, time: "17:58:39", platform: "Flipkart", status: 200, message: "Parsed 182 product cards · 96% match confidence", tone: "ok" },
  { id: 3, time: "17:58:21", platform: "Myntra", status: 429, message: "Rate limit reached · retry window in 42 seconds", tone: "warn" },
  { id: 4, time: "17:57:55", platform: "Nykaa", status: 200, message: "Captured 121 offers · inventory signals attached", tone: "ok" },
  { id: 5, time: "17:57:08", platform: "Croma", status: 204, message: "No delta returned · catalog remains in sync", tone: "ok" },
];
const formatTime = () => new Date().toLocaleTimeString([], { hour12: false });
function StateBadge({ state }: { state: PlatformState }) { const tone = state === "active" || state === "running" ? "emerald" : state === "alert" ? "rose" : "amber"; return <Badge tone={tone} dot>{state === "running" ? "running" : state}</Badge>; }
function PlatformCard({ platform, onRun }: { platform: Platform; onRun: () => void }) { return <motion.div layout whileHover={{ y: -3 }} className="scraper-platform-card"><div className="scraper-card-head"><div className="scraper-logo" style={{ borderColor: `${platform.color}66`, color: platform.color }}>{platform.code}</div><StateBadge state={platform.state} /></div><h3>{platform.name}</h3><div className="scraper-meta"><span><Clock3 size={12} /> every {platform.cadence}</span><span><Activity size={12} /> {platform.latency}</span></div><div className="scraper-progress"><div><span>Coverage</span><strong>{platform.coverage}%</strong></div><i><b style={{ width: `${platform.coverage}%`, background: platform.color }} /></i></div><div className="scraper-card-foot"><span>{platform.items.toLocaleString()} items · HTTP {platform.lastStatus}</span><button type="button" onClick={onRun} disabled={platform.state === "running"} aria-label={`Run ${platform.name} scraper`}><Play size={13} /> Run now</button></div></motion.div>; }
function formatAlertAge(timestamp: string) { const minutes = Math.max(0, Math.floor((Date.now() - new Date(timestamp).getTime()) / 60000)); return minutes < 1 ? "just now" : `${minutes}m ago`; }

export default function ScraperHubPage() {
  const { data } = usePricingData();
  const { toasts, push, dismiss } = useToasts();
  const [platforms, setPlatforms] = useState(initialPlatforms);
  const [logs, setLogs] = useState(seedLogs);
  const [alerts, setAlerts] = useState<PriceDropAlert[]>([]);
  const [runningAll, setRunningAll] = useState(false);
  const [query, setQuery] = useState("");
  const [loadingAlerts, setLoadingAlerts] = useState(false);
  const visible = useMemo(() => platforms.filter((platform) => platform.name.toLowerCase().includes(query.toLowerCase())), [platforms, query]);

  const refreshAlerts = async (announce = false) => { setLoadingAlerts(true); try { const next = await getPriceDropAlerts("open"); setAlerts(next); if (announce) push(next.length ? `${next.length} open competitor drop alert${next.length === 1 ? "" : "s"}.` : "No open competitor drop alerts.", next.length ? "error" : "info"); } catch { if (announce) push("Alert service is unavailable; the last snapshot is retained.", "error"); } finally { setLoadingAlerts(false); } };
  useEffect(() => { void refreshAlerts(); const timer = window.setInterval(() => void refreshAlerts(), 15000); return () => window.clearInterval(timer); }, []);

  const run = async (platformName: string) => { const product: Product | undefined = data.products[0]; if (!product) { push("No catalog product is available for a scraper run.", "error"); return; } setPlatforms((items) => items.map((item) => item.name === platformName ? { ...item, state: "running" } : item)); setLogs((items) => [{ id: Date.now(), time: formatTime(), platform: platformName, status: "…" as const, message: `Opening target and matching ${product.sku} · awaiting response`, tone: "ok" as const }, ...items].slice(0, 12)); try { await apiClient.get(`/recommendations/stream-scrape/${product.id}`, { responseType: "text", timeout: 12000 }); setLogs((items) => [{ id: Date.now(), time: formatTime(), platform: platformName, status: 200, message: `Stream completed · ${product.name} normalized into pricing pipeline`, tone: "ok" as const }, ...items].slice(0, 12)); push(`${platformName} scrape completed and normalized.`); await refreshAlerts(); } catch { setLogs((items) => [{ id: Date.now(), time: formatTime(), platform: platformName, status: 503, message: "Live stream unavailable · supervisor retained previous snapshot", tone: "warn" as const }, ...items].slice(0, 12)); push(`${platformName} is unavailable; previous snapshot retained.`, "error"); } finally { setPlatforms((items) => items.map((item) => item.name === platformName ? { ...item, state: item.lastStatus === 429 ? "alert" : "active" } : item)); } };
  const acknowledge = async (alert: PriceDropAlert) => { try { await acknowledgePriceDropAlert(alert.id); setAlerts((items) => items.filter((item) => item.id !== alert.id)); push(`${alert.competitorName} alert acknowledged.`); } catch { push("Alert could not be acknowledged.", "error"); } };
  const runAll = async () => { setRunningAll(true); push("Supervisor run started across all enabled targets.", "info"); for (const platform of platforms.filter((item) => item.state !== "alert")) await run(platform.name); setRunningAll(false); };

  return <div className="page-stack"><ToastStack toasts={toasts} dismiss={dismiss} /><header className="page-header"><div><p className="eyebrow"><Radio size={12} /> Scraper intelligence hub <span className="live-dot" /></p><h1>Market signals, <em>without the noise.</em></h1><p className="page-lede">A quiet, operational view of every marketplace sensor feeding the pricing engine.</p></div><div className="header-controls"><div className="control-chip"><span className="live-dot" /> Supervisor online</div><Button onClick={() => void runAll()} disabled={runningAll}>{runningAll ? <Loader2 className="spin" size={14} /> : <RefreshCw size={14} />} {runningAll ? "Running targets…" : "Run all targets"}</Button></div></header><div className="scraper-summary-grid"><div><Wifi size={16} /><span><strong>{platforms.filter((item) => item.state === "active").length}/8</strong><small>targets active</small></span></div><div><Terminal size={16} /><span><strong>{platforms.reduce((sum, item) => sum + item.items, 0).toLocaleString()}</strong><small>items last cycle</small></span></div><div><CheckCircle2 size={16} /><span><strong>98.4%</strong><small>normalized cleanly</small></span></div><div><BellRing size={16} /><span><strong>{alerts.length}</strong><small>open price-drop alerts</small></span></div></div>
    <GlassCard className="price-alert-panel"><div className="card-heading"><SectionTitle eyebrow="Automated guardrail" title="Sudden competitor drops" description="Alerts fire when a marketplace price falls past the configured percentage and INR floor, then cool down to prevent duplicate noise." /><Button variant="secondary" onClick={() => void refreshAlerts(true)} disabled={loadingAlerts}>{loadingAlerts ? <Loader2 className="spin" size={14} /> : <RefreshCw size={14} />} Refresh alerts</Button></div>{alerts.length === 0 ? <div className="alert-empty"><CheckCircle2 size={17} /><span>No open competitor drops. The supervisor is watching all eight marketplaces.</span></div> : <div className="alert-list"><AnimatePresence initial={false}>{alerts.map((alert) => <motion.div key={alert.id} initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: 8 }} className="price-alert-row"><div className="alert-icon"><CircleAlert size={15} /></div><div className="alert-copy"><strong>{alert.competitorName} dropped {alert.dropPercent.toFixed(1)}%</strong><span>{alert.productName} · {alert.sku} · {formatAlertAge(alert.detectedAt)}</span></div><div className="alert-prices"><strong>₹{alert.currentPrice.toLocaleString()}</strong><span>from ₹{alert.previousPrice.toLocaleString()}</span></div><button type="button" className="alert-dismiss" onClick={() => void acknowledge(alert)} aria-label={`Acknowledge ${alert.competitorName} alert`}><X size={14} /></button></motion.div>)}</AnimatePresence></div>}</GlassCard>
    <section className="scraper-section"><div className="section-title-row"><SectionTitle eyebrow="Target matrix" title="Eight marketplace sensors" description="Each agent is monitored for freshness, response health, and normalization coverage." /><div className="search-field"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter targets" aria-label="Filter targets" /></div></div><div className="scraper-platform-grid">{visible.map((platform) => <PlatformCard key={platform.name} platform={platform} onRun={() => void run(platform.name)} />)}</div></section><section className="scraper-terminal-layout"><GlassCard className="terminal-card"><div className="card-heading"><SectionTitle eyebrow="Execution terminal" title="Supervisor logs" description="Recent requests, status codes, and item counts from the current run." /><Badge tone="emerald" dot>Streaming</Badge></div><div className="terminal-window"><div className="terminal-top"><span><i /><i /><i /></span><small>scraper-supervisor / live</small><Command size={13} /></div><div className="terminal-lines"><AnimatePresence initial={false}>{logs.map((log) => <motion.div key={log.id} initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} className="terminal-line"><span className="terminal-time">{log.time}</span><span className="terminal-platform">{log.platform}</span><strong className={log.tone}>{log.status}</strong><span className="terminal-message">{log.message}</span></motion.div>)}</AnimatePresence><div className="terminal-cursor"><span>›</span> supervisor ready<span className="cursor-blink">_</span></div></div></div></GlassCard><GlassCard className="pipeline-card"><div className="card-heading"><SectionTitle eyebrow="Pipeline health" title="From scrape to signal" description="The normalized payload moves directly into competitor intelligence and price recommendations." /></div><div className="pipeline-steps"><div className="pipeline-step active"><span>01</span><strong>Fetch</strong><small>8 target URLs</small></div><div className="pipeline-connector" /><div className="pipeline-step active"><span>02</span><strong>Normalize</strong><small>price · stock · URL</small></div><div className="pipeline-connector" /><div className="pipeline-step active"><span>03</span><strong>Score</strong><small>match confidence</small></div><div className="pipeline-connector" /><div className="pipeline-step"><span>04</span><strong>Reprice</strong><small>guardrail review</small></div></div><div className="pipeline-callout"><Terminal size={15} /><p><strong>Last cycle completed in 8m 14s.</strong><br />1,248 records were available to the pricing engine.</p></div><Button variant="secondary" onClick={() => push("Pipeline diagnostics downloaded.", "info")}><ExternalLink size={14} /> View diagnostics</Button></GlassCard></section></div>;
}
