import { motion } from "framer-motion";
import { ArrowRight, Bot, Check, ChevronRight, CircleAlert, Filter, Gauge, Package, Search, Sparkles, Target, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { mockDashboard } from "../lib/mockData";
import { cn, money } from "../lib/utils";
import { Badge, Button, EmptyState, GlassCard, IconMark, SectionTitle, useToasts, ToastStack } from "../components/ui";

type SecondaryKind = "catalog" | "approvals" | "agents";
export default function SecondaryPage({ kind }: { kind: SecondaryKind }) {
  const navigate = useNavigate();
  const { toasts, push, dismiss } = useToasts();
  const [query, setQuery] = useState("");
  const [approved, setApproved] = useState<string[]>([]);
  const title = kind === "catalog" ? "Catalog intelligence" : kind === "approvals" ? "Approval workspace" : "AI pricing agents";
  const subtitle = kind === "catalog" ? "Explore every item, signal, and price movement in one searchable layer." : kind === "approvals" ? "Make fast, explainable decisions on the recommendations that matter." : "Watch autonomous agents learn, reason, and execute pricing strategies.";
  const products = useMemo(() => mockDashboard.products.filter((product) => `${product.name} ${product.sku}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const metrics = kind === "agents" ? [{ label: "Agents online", value: "06", icon: Bot }, { label: "Decisions today", value: "312", icon: Sparkles }, { label: "Avg. confidence", value: "92%", icon: Gauge }] : [{ label: "Items in view", value: "1,284", icon: Package }, { label: "Need attention", value: "18", icon: CircleAlert }, { label: "Ready to act", value: "24", icon: Target }];
  return <div className="page-stack"><ToastStack toasts={toasts} dismiss={dismiss} /><header className="page-header compact-header"><div><p className="eyebrow">Workspace module</p><h1>{title}, <em>made legible.</em></h1><p className="page-lede">{subtitle}</p></div><Button onClick={() => push("Export prepared for your workspace.", "info")}>Export view <ArrowRight size={15} /></Button></header><section className="secondary-metrics">{metrics.map((metric) => <GlassCard key={metric.label}><metric.icon size={18} className="text-indigo" /><span><strong>{metric.value}</strong><small>{metric.label}</small></span></GlassCard>)}</section>{kind === "agents" ? <AgentConsole onToast={push} /> : <GlassCard className="table-card"><div className="card-heading table-heading"><SectionTitle eyebrow={kind === "approvals" ? "Decision queue" : "Live catalog"} title={kind === "approvals" ? "Recommendations awaiting you" : "All catalog items"} description="Search, inspect, and take action without leaving the signal." /><div className="table-actions"><div className="search-field"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by product or SKU" /></div><Button variant="secondary" onClick={() => push("Advanced filters are ready.", "info")}><Filter size={14} /> Filter</Button></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Product</th><th>Current</th><th>AI target</th><th>Margin</th><th>Status</th><th>Action</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><div className="product-cell"><IconMark initials={product.initials} color={product.image} /><span><strong>{product.name}</strong><small>{product.sku} · {product.category}</small></span></div></td><td className="mono">{money(product.currentPrice)}</td><td className="mono target-price">{money(product.targetPrice)}</td><td className="mono">{product.margin.toFixed(1)}%</td><td><Badge tone={product.status === "recommended" ? "violet" : product.status === "approved" ? "emerald" : "amber"} dot>{approved.includes(product.id) ? "Approved" : product.status}</Badge></td><td><Button className="table-button" variant={approved.includes(product.id) ? "secondary" : "primary"} onClick={() => { setApproved([...approved, product.id]); push(`${product.name} moved to the execution queue.`); }}>{approved.includes(product.id) ? <><Check size={13} /> Queued</> : "Review"}</Button></td></tr>)}</tbody></table>{!products.length && <EmptyState title="Nothing found" description="Try another product name, category, or SKU." />}</div><div className="table-footer"><span>Showing {products.length} prioritized records</span><button className="text-button" onClick={() => navigate("/dashboard")}>Back to command center <ChevronRight size={14} /></button></div></GlassCard>}</div>;
}

function AgentConsole({ onToast }: { onToast: (message: string, tone?: "success" | "error" | "info") => void }) {
  const agents = [{ name: "Demand Forecaster", status: "Learning", color: "indigo", description: "Models price elasticity from 18,420 historical observations.", progress: 82 }, { name: "Competitor Sentinel", status: "Monitoring", color: "emerald", description: "Scanning three marketplaces for undercuts and buy-box shifts.", progress: 96 }, { name: "Margin Guardian", status: "Ready", color: "violet", description: "Protecting your contribution margin across active pricing rules.", progress: 91 }, { name: "Inventory Navigator", status: "Monitoring", color: "rose", description: "Balancing cover days, demand velocity, and clearance risk.", progress: 74 }];
  return <div className="agent-console-grid">{agents.map((agent, index) => <motion.div key={agent.name} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .07 }}><GlassCard className={cn("agent-card", `agent-accent-${agent.color}`)}><div className="agent-card-top"><span className="agent-avatar"><Bot size={18} /></span><Badge tone={agent.color as "indigo" | "emerald" | "violet" | "rose"} dot>{agent.status}</Badge></div><h3>{agent.name}</h3><p>{agent.description}</p><div className="agent-progress"><div><span>Signal quality</span><strong>{agent.progress}%</strong></div><i><b style={{ width: `${agent.progress}%` }} /></i></div><button className="text-button" onClick={() => onToast(`${agent.name} detail view opened.`, "info")}>Inspect agent <ArrowRight size={14} /></button></GlassCard></motion.div>)}</div>;
}
