import { motion } from "framer-motion";
import { ArrowRight, Bot, Check, ChevronRight, CircleAlert, Clock3, Database, Filter, Gauge, MailCheck, Package, Search, Sparkles, Target } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { mockDashboard } from "../lib/mockData";
import { getApprovalHistory } from "../services/api";
import type { ApprovalAuditEvent } from "../types/domain";
import { cn, money } from "../lib/utils";
import { Badge, Button, EmptyState, GlassCard, IconMark, SectionTitle, useToasts, ToastStack } from "../components/ui";

type SecondaryKind = "catalog" | "approvals" | "agents";

export default function SecondaryPage({ kind }: { kind: SecondaryKind }) {
  const navigate = useNavigate();
  const { toasts, push, dismiss } = useToasts();
  const [query, setQuery] = useState("");
  const [approved, setApproved] = useState<string[]>([]);
  const [history, setHistory] = useState<ApprovalAuditEvent[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const title = kind === "catalog" ? "Catalog intelligence" : kind === "approvals" ? "Approval workspace" : "AI pricing agents";
  const subtitle = kind === "catalog" ? "Explore every item, signal, and price movement in one searchable layer." : kind === "approvals" ? "Make fast, explainable decisions on the recommendations that matter." : "Watch autonomous agents learn, reason, and execute pricing strategies.";
  const products = useMemo(() => mockDashboard.products.filter((product) => `${product.name} ${product.sku}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const metrics = kind === "agents" ? [{ label: "Agents online", value: "06", icon: Bot }, { label: "Decisions today", value: "312", icon: Sparkles }, { label: "Avg. confidence", value: "92%", icon: Gauge }] : [{ label: "Items in view", value: "1,284", icon: Package }, { label: "Need attention", value: "18", icon: CircleAlert }, { label: "Ready to act", value: "24", icon: Target }];
  useEffect(() => { if (kind !== "approvals") return; setHistoryLoading(true); void getApprovalHistory().then(setHistory).catch(() => push("Audit history is unavailable; showing the workspace shell.", "error")).finally(() => setHistoryLoading(false)); }, [kind, push]);
  return <div className="page-stack"><ToastStack toasts={toasts} dismiss={dismiss} /><header className="page-header compact-header"><div><p className="eyebrow">Workspace module</p><h1>{title}, <em>made legible.</em></h1><p className="page-lede">{subtitle}</p></div><Button onClick={() => push("Export prepared for your workspace.", "info")}>Export view <ArrowRight size={15} /></Button></header><section className="secondary-metrics">{metrics.map((metric) => <GlassCard key={metric.label}><metric.icon size={18} className="text-indigo" /><span><strong>{metric.value}</strong><small>{metric.label}</small></span></GlassCard>)}</section>{kind === "agents" ? <AgentConsole onToast={push} /> : kind === "approvals" ? <ApprovalAuditPanel history={history} loading={historyLoading} onRefresh={() => { setHistoryLoading(true); void getApprovalHistory().then(setHistory).finally(() => setHistoryLoading(false)); }} /> : <CatalogTable products={products} query={query} setQuery={setQuery} approved={approved} setApproved={setApproved} onToast={push} navigate={navigate} />}</div>;
}

function CatalogTable({ products, query, setQuery, approved, setApproved, onToast, navigate }: { products: typeof mockDashboard.products; query: string; setQuery: (value: string) => void; approved: string[]; setApproved: (value: string[]) => void; onToast: (message: string, tone?: "success" | "error" | "info") => void; navigate: ReturnType<typeof useNavigate> }) {
  return <GlassCard className="table-card"><div className="card-heading table-heading"><SectionTitle eyebrow="Live catalog" title="All catalog items" description="Search, inspect, and take action without leaving the signal." /><div className="table-actions"><div className="search-field"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by product or SKU" /></div><Button variant="secondary" onClick={() => onToast("Advanced filters are ready.", "info")}><Filter size={14} /> Filter</Button></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Product</th><th>Current</th><th>AI target</th><th>Margin</th><th>Status</th><th>Action</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><div className="product-cell"><IconMark initials={product.initials} color={product.image} /><span><strong>{product.name}</strong><small>{product.sku} · {product.category}</small></span></div></td><td className="mono">{money(product.currentPrice)}</td><td className="mono target-price">{money(product.targetPrice)}</td><td className="mono">{product.margin.toFixed(1)}%</td><td><Badge tone={product.status === "recommended" ? "violet" : product.status === "approved" ? "emerald" : "amber"} dot>{approved.includes(product.id) ? "Approved" : product.status}</Badge></td><td><Button className="table-button" variant={approved.includes(product.id) ? "secondary" : "primary"} onClick={() => { setApproved([...approved, product.id]); onToast(`${product.name} moved to the execution queue.`); }}>{approved.includes(product.id) ? <><Check size={13} /> Queued</> : "Review"}</Button></td></tr>)}</tbody></table>{!products.length && <EmptyState title="Nothing found" description="Try another product name, category, or SKU." />}</div><div className="table-footer"><span>Showing {products.length} prioritized records</span><button className="text-button" onClick={() => navigate("/dashboard")}>Back to command center <ChevronRight size={14} /></button></div></GlassCard>;
}

function ApprovalAuditPanel({ history, loading, onRefresh }: { history: ApprovalAuditEvent[]; loading: boolean; onRefresh: () => void }) {
  return <GlassCard className="audit-history-card"><div className="card-heading"><SectionTitle eyebrow="Audit trail & history" title="Every price action, explained" description="A chronological record of decision, rationale, database sync, and notification delivery." /><Button variant="secondary" onClick={onRefresh} disabled={loading}>{loading ? "Refreshing…" : "Refresh history"}</Button></div>{history.length === 0 ? <EmptyState title={loading ? "Loading audit history" : "No action history yet"} description="Approved, rejected, and rolled-back price actions will appear here with their full rationale." /> : <div className="audit-timeline">{history.map((event) => <motion.div key={event.id} initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} className="audit-event"><div className={cn("audit-marker", event.actionType === "approve" ? "success" : event.actionType === "reject" ? "danger" : "violet")}><Clock3 size={14} /></div><div className="audit-event-body"><div className="audit-event-top"><div><Badge tone={event.actionType === "approve" ? "emerald" : event.actionType === "reject" ? "rose" : "violet"} dot>{event.actionType === "approve" ? "APPROVED" : event.actionType === "reject" ? "REJECTED" : "ROLLED BACK"}</Badge><h3>{event.productName}</h3><span className="audit-sku">{event.sku} · {new Date(event.timestamp).toLocaleString()}</span></div><div className="audit-statuses"><span><MailCheck size={13} /> Email {event.emailSentStatus === "sent" ? "Sent ✓" : event.emailSentStatus}</span><span><Database size={13} /> DB Synced ✓</span></div></div><div className="audit-price-row"><span>₹{event.previousPrice.toLocaleString()} → <strong>₹{event.executedPrice.toLocaleString()}</strong></span><span>{event.userEmail}</span></div><details><summary>View LLM rationale</summary><p>{event.llmStatement}</p></details></div></motion.div>)}</div>}</GlassCard>;
}

function AgentConsole({ onToast }: { onToast: (message: string, tone?: "success" | "error" | "info") => void }) {
  const agents = [{ name: "Demand Forecaster", status: "Learning", color: "indigo", description: "Models price elasticity from 18,420 historical observations.", progress: 82 }, { name: "Competitor Sentinel", status: "Monitoring", color: "emerald", description: "Scanning eight marketplaces for undercuts and buy-box shifts.", progress: 96 }, { name: "Margin Guardian", status: "Ready", color: "violet", description: "Protecting your contribution margin across active pricing rules.", progress: 91 }, { name: "Inventory Navigator", status: "Monitoring", color: "rose", description: "Balancing cover days, demand velocity, and clearance risk.", progress: 74 }];
  return <div className="agent-console-grid">{agents.map((agent, index) => <motion.div key={agent.name} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .07 }}><GlassCard className={cn("agent-card", `agent-accent-${agent.color}`)}><div className="agent-card-top"><span className="agent-avatar"><Bot size={18} /></span><Badge tone={agent.color as "indigo" | "emerald" | "violet" | "rose"} dot>{agent.status}</Badge></div><h3>{agent.name}</h3><p>{agent.description}</p><div className="agent-progress"><div><span>Signal quality</span><strong>{agent.progress}%</strong></div><i><b style={{ width: `${agent.progress}%` }} /></i></div><button className="text-button" onClick={() => onToast(`${agent.name} detail view opened.`, "info")}>Inspect agent <ArrowRight size={14} /></button></GlassCard></motion.div>)}</div>;
}
