"""add agent analysis

Revision ID: 019544ea1e46
Revises: be75149056b7
Create Date: 2026-05-15 00:47:54.340918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019544ea1e46'
down_revision = 'be75149056b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_analysis', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_recommendations', schema=None) as batch_op:
        batch_op.drop_column('agent_analysis')

    # ### end Alembic commands ###
