"""Initial clean schema

Revision ID: be75149056b7
Revises: 
Create Date: 2026-05-14 14:27:17.889458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be75149056b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auto_execute_threshold', sa.Float(), nullable=False),
    sa.Column('minimum_margin', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_rules_organization_id'), ['organization_id'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('inventory_quantity', sa.Integer(), nullable=True),
    sa.Column('min_margin_percentage', sa.Float(), nullable=True),
    sa.Column('recommendation_status', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=64), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('competitor_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('competitor_price', sa.Float(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_prices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_prices_product_id'), ['product_id'], unique=False)

    op.create_table('demand_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('seasonal_factor', sa.Float(), nullable=False),
    sa.Column('sku_velocity', sa.Float(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_signals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_signals_product_id'), ['product_id'], unique=False)

    op.create_table('pricing_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_price', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_by_agent', sa.String(length=128), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_recommendations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_recommendations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_recommendations_status'), ['status'], unique=False)

    op.create_table('approval_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('previous_price', sa.Float(), nullable=True),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['pricing_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_actions_recommendation_id'), ['recommendation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_actions_recommendation_id'))

    op.drop_table('approval_actions')
    with op.batch_alter_table('pricing_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_pricing_recommendations_product_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_recommendations_organization_id'))

    op.drop_table('pricing_recommendations')
    with op.batch_alter_table('demand_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_signals_product_id'))
        batch_op.drop_index(batch_op.f('ix_demand_signals_organization_id'))

    op.drop_table('demand_signals')
    with op.batch_alter_table('competitor_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_prices_product_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_prices_organization_id'))

    op.drop_table('competitor_prices')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_organization_id'))

    op.drop_table('products')
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_rules_organization_id'))

    op.drop_table('pricing_rules')
    op.drop_table('organizations')
    # ### end Alembic commands ###
